### ISSUE TITLE
@Deprecated code should not be used

### ISSUE THREAD

**Issue by YajingLiu2357** [YajingLiu2357/robocodeFall2024#15]
**Describe the technical debt**
Once deprecated, classes, and interfaces, and their members should be avoided, rather than used, inherited or extended. Deprecation is a warning that the class or interface has been superseded, and will eventually be removed. The deprecation period allows you to make a smooth transition away from the aging, soon-to-be-retired technology.

**Expected behavior**
Don't override a deprecated method or explicitly mark it as "@Deprecated".

**Screenshots**
<img width="1512" alt="Screenshot 2024-10-04 at 11 37 02 PM" src="https://github.com/user-attachments/assets/20f088fd-c0d6-45bc-a293-15bed3c4c432">

**Comment by 0matleb2** [comment]
This fix looks like it could be unsafe. If there are any calls to finalize on an object of this type, it will no longer cleanup. Can you confirm that cleanup is never used at runtime or is unnecessary?

**Comment by YajingLiu2357** [comment]
> This fix looks like it could be unsafe. If there are any calls to finalize on an object of this type, it will no longer cleanup. Can you confirm that cleanup is never used at runtime or is unnecessary?

I am not sure about how this finalize function executes in run time. This function has 0 references as shown in IDE so it seems to be never called in the run time. I can change it back if it is needed.

**Comment by 0matleb2** [comment]
Some frameworks can enable calls to methods at runtime that wouldn't show up as a reference in the IDE. While it might be safe to remove this if we understand the system well enough to rule out that possibility (I don't), another alternative that should resolve your issue is marking the overridden method as deprecated.

**Comment by YajingLiu2357** [comment]
Got it! Thank you for your explanation. I will fix it in the next commit.
